# Import Libraries

In [1]:
import pandas as pd
import numpy as np

from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB

from sklearn.model_selection import train_test_split

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

import re
import glob
import os

In [4]:
import os
current_dir = os.getcwd()
current_dir


folder_path = "movie_reviews\\"
folder_path

'movie_reviews\\'

In [5]:
os.listdir(folder_path)

['neg', 'pos']

In [18]:
negative_folder_path = folder_path + 'neg'
positive_folder_path = folder_path + 'pos'

negative_folder_path
positive_folder_path

negative_text_files = glob.glob(f"{negative_folder_path}\\*.txt")
positive_text_files = glob.glob(f"{positive_folder_path}\\*.txt")

In [19]:
positive_text_files

['movie_reviews\\pos\\cv000_29590.txt',
 'movie_reviews\\pos\\cv001_18431.txt',
 'movie_reviews\\pos\\cv002_15918.txt',
 'movie_reviews\\pos\\cv003_11664.txt',
 'movie_reviews\\pos\\cv004_11636.txt',
 'movie_reviews\\pos\\cv005_29443.txt',
 'movie_reviews\\pos\\cv006_15448.txt',
 'movie_reviews\\pos\\cv007_4968.txt',
 'movie_reviews\\pos\\cv008_29435.txt',
 'movie_reviews\\pos\\cv009_29592.txt',
 'movie_reviews\\pos\\cv010_29198.txt',
 'movie_reviews\\pos\\cv011_12166.txt',
 'movie_reviews\\pos\\cv012_29576.txt',
 'movie_reviews\\pos\\cv013_10159.txt',
 'movie_reviews\\pos\\cv014_13924.txt',
 'movie_reviews\\pos\\cv015_29439.txt',
 'movie_reviews\\pos\\cv016_4659.txt',
 'movie_reviews\\pos\\cv017_22464.txt',
 'movie_reviews\\pos\\cv018_20137.txt',
 'movie_reviews\\pos\\cv019_14482.txt',
 'movie_reviews\\pos\\cv020_8825.txt',
 'movie_reviews\\pos\\cv021_15838.txt',
 'movie_reviews\\pos\\cv022_12864.txt',
 'movie_reviews\\pos\\cv023_12672.txt',
 'movie_reviews\\pos\\cv024_6778.txt',
 'mo

In [20]:
len(positive_text_files)

1000

In [21]:
len(negative_text_files)

1000

In [9]:
review_list = []
for file_name in negative_text_files:
    f = open(file_name)
    text = f.read()
    text = text.lower()
    text = re.sub('[^a-z]+',' ', text)
#     print(text)
    f.close()
    review_list.append(text)
    
    
    
for file_name in positive_text_files:
    f = open(file_name)
    text = f.read()
    text = text.lower()
    text = re.sub('[^a-z]+',' ', text)
#     print(text)
    f.close()
    review_list.append(text)

In [22]:
len(review_list)

2000

In [28]:
neg_target = np.zeros(len(negative_text_files), dtype = int)

pos_target = np.ones(len(positive_text_files), dtype = int)


In [92]:
y = np.append(neg_target,pos_target)
y = pd.Series(y)
y

0       0
1       0
2       0
3       0
4       0
       ..
1995    1
1996    1
1997    1
1998    1
1999    1
Length: 2000, dtype: int32

# Bag of Words

In [109]:
# Countvectorizer

cnt_vectorizer = CountVectorizer(stop_words='english', min_df=0.05)
x_count_vct = cnt_vectorizer.fit_transform(review_list)
x = pd.DataFrame(x_count_vct.toarray(), columns=cnt_vectorizer.get_feature_names())
x

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


ability  able  absolutely  act  acting  action  actor  actors  actress  \
0           0     0           0    0       0       0      0       1        0   
1           0     0           0    0       2       1      0       0        0   
2           0     0           0    0       1       0      0       0        0   
3           0     1           0    0       0       0      0       1        0   
4           0     0           0    0       0       0      2       0        0   
...       ...   ...         ...  ...     ...     ...    ...     ...      ...   
1995        0     0           0    0       1       0      0       0        0   
1996        0     0           0    0       0       0      1       0        0   
1997        1     0           0    0       0       3      0       0        0   
1998        0     0           0    0       0       0      1       2        0   
1999        0     0           0    0       0       0      0       0        0   

      actual  ...  writers  writing  written  wrong  wrote  year  years  yes  \
0          0  ...        0        0        0      0      0     0      1    0   
1          0  ...        0        0        0      0      0     0      0    0   
2          0  ...        0        0        1      1      0     0      0    0   
3          0  ...        0        0        0      0      0     1      0    0   
4          0  ...        0        0        0      0      0     0      0    0   
...      ...  ...      ...      ...      ...    ...    ...   ...    ...  ...   
1995       0  ...        0        1        1      0      0     3      0    0   
1996       0  ...        0        0        0      0      0     0      0    0   
1997       1  ...        0        0        0      0      1     0      0    0   
1998       0  ...        0        0        0      0      0     1      0    0   
1999       0  ...        0        0        1      0      0     0      0    0   

      york  young  
0        0      0  
1        0      0  
2        0      1  
3        0      0  
4        0      0  
...    ...    ...  
1995     0      0  
1996     0      0  
1997     0      2  
1998     0      0  
1999     0      0  

[2000 rows x 886 columns]

# TF-IDF Vectorizer

In [94]:
tfidf_vectorizer = TfidfVectorizer(stop_words='english', min_df=0.05)
x_tfidf = tfidf_vectorizer.fit_transform(review_list)
x = pd.DataFrame(x_tfidf.toarray(), columns=tfidf_vectorizer.get_feature_names())


# Train Test Split

In [95]:
x_train,x_test,y_train,y_test = train_test_split(w_tf,y, test_size=0.2, random_state=1,
                                                 stratify=y)

# Model Training

# 1. GaussianNB()

In [96]:
gnb_model = GaussianNB()
gnb_model.fit(x_train, y_train)

GaussianNB()

In [97]:
y_pred = gnb_model.predict(x_test)


cnf_matrix = confusion_matrix(y_test,y_pred)
print('Confusion matrix :\n', cnf_matrix)


acc_score = accuracy_score(y_test,y_pred)
print('Accuracy score :\n', acc_score)

clf_report = classification_report(y_test,y_pred)
print('Classification report :\n', clf_report)

Confusion matrix :
 [[124  76]
 [ 58 142]]
Accuracy score :
 0.665
Classification report :
               precision    recall  f1-score   support

           0       0.68      0.62      0.65       200
           1       0.65      0.71      0.68       200

    accuracy                           0.67       400
   macro avg       0.67      0.67      0.66       400
weighted avg       0.67      0.67      0.66       400



In [98]:
y_pred_train = gnb_model.predict(x_train)


cnf_matrix = confusion_matrix(y_train,y_pred_train)
print('Confusion matrix :\n', cnf_matrix)


acc_score = accuracy_score(y_train,y_pred_train)
print('Accuracy score :\n', acc_score)

clf_report = classification_report(y_train,y_pred_train)
print('Classification report :\n', clf_report)

Confusion matrix :
 [[799   1]
 [ 17 783]]
Accuracy score :
 0.98875
Classification report :
               precision    recall  f1-score   support

           0       0.98      1.00      0.99       800
           1       1.00      0.98      0.99       800

    accuracy                           0.99      1600
   macro avg       0.99      0.99      0.99      1600
weighted avg       0.99      0.99      0.99      1600



# 2. MultinomialNB

In [99]:
mnb_model = MultinomialNB()
mnb_model.fit(x_train,y_train)

MultinomialNB()

In [100]:
y_pred = mnb_model.predict(x_test)


cnf_matrix = confusion_matrix(y_test,y_pred)
print('Confusion matrix :\n', cnf_matrix)


acc_score = accuracy_score(y_test,y_pred)
print('Accuracy score :\n', acc_score)

clf_report = classification_report(y_test,y_pred)
print('Classification report :\n', clf_report)

Confusion matrix :
 [[176  24]
 [ 49 151]]
Accuracy score :
 0.8175
Classification report :
               precision    recall  f1-score   support

           0       0.78      0.88      0.83       200
           1       0.86      0.76      0.81       200

    accuracy                           0.82       400
   macro avg       0.82      0.82      0.82       400
weighted avg       0.82      0.82      0.82       400



In [101]:
y_pred_train = mnb_model.predict(x_train)


cnf_matrix = confusion_matrix(y_train,y_pred_train)
print('Confusion matrix :\n', cnf_matrix)


acc_score = accuracy_score(y_train,y_pred_train)
print('Accuracy score :\n', acc_score)

clf_report = classification_report(y_train,y_pred_train)
print('Classification report :\n', clf_report)

Confusion matrix :
 [[772  28]
 [ 50 750]]
Accuracy score :
 0.95125
Classification report :
               precision    recall  f1-score   support

           0       0.94      0.96      0.95       800
           1       0.96      0.94      0.95       800

    accuracy                           0.95      1600
   macro avg       0.95      0.95      0.95      1600
weighted avg       0.95      0.95      0.95      1600



# 3. BernoulliNB

In [102]:
bnb_model = BernoulliNB()
bnb_model.fit(x_train,y_train)

BernoulliNB()

In [103]:
y_pred = bnb_model.predict(x_test)


cnf_matrix = confusion_matrix(y_test,y_pred)
print('Confusion matrix :\n', cnf_matrix)


acc_score = accuracy_score(y_test,y_pred)
print('Accuracy score :\n', acc_score)

clf_report = classification_report(y_test,y_pred)
print('Classification report :\n', clf_report)

Confusion matrix :
 [[176  24]
 [ 53 147]]
Accuracy score :
 0.8075
Classification report :
               precision    recall  f1-score   support

           0       0.77      0.88      0.82       200
           1       0.86      0.73      0.79       200

    accuracy                           0.81       400
   macro avg       0.81      0.81      0.81       400
weighted avg       0.81      0.81      0.81       400



In [104]:
y_pred_train = bnb_model.predict(x_train)


cnf_matrix = confusion_matrix(y_train,y_pred_train)
print('Confusion matrix :\n', cnf_matrix)


acc_score = accuracy_score(y_train,y_pred_train)
print('Accuracy score :\n', acc_score)

clf_report = classification_report(y_train,y_pred_train)
print('Classification report :\n', clf_report)

Confusion matrix :
 [[782  18]
 [121 679]]
Accuracy score :
 0.913125
Classification report :
               precision    recall  f1-score   support

           0       0.87      0.98      0.92       800
           1       0.97      0.85      0.91       800

    accuracy                           0.91      1600
   macro avg       0.92      0.91      0.91      1600
weighted avg       0.92      0.91      0.91      1600



# Advantages:

# Disadvantages:

# Application: